FROM node:20-bookworm-slim AS dev
WORKDIR /app
ENV NODE_ENV=development
# Workarounds/estabilidade no dev
ENV NEXT_DISABLE_TURBOPACK=1
ENV WATCHPACK_POLLING=true

COPY package.json package-lock.json ./
# Instala TODAS as deps (inclui dev), necessário para `npm run dev`
RUN npm ci --fetch-retries=5 --fetch-retry-maxtimeout=600000

COPY . .
EXPOSE 4000
CMD ["npm", "run", "dev"]

FROM node:20-bookworm-slim AS builder
WORKDIR /app
ENV NODE_ENV=development
COPY package.json package-lock.json ./
RUN npm ci --fetch-retries=5 --fetch-retry-maxtimeout=600000
COPY . .
RUN npm run build

FROM node:20-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY package.json package-lock.json ./
RUN npm ci --omit=dev --fetch-retries=5 --fetch-retry-maxtimeout=600000
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
EXPOSE 4000
CMD ["npm", "run", "start"]
